kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ro-user-role
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces", "services", "ingresses", "nodes", "daemonset"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["list", "create"]
- apiGroups: ["apps"]      
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
