apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    k3scluster.tech {
        template IN CAA {
            match (^|.*\.)k3scluster\.tech
            answer "{{ .Name }} 3600 IN CAA 0 issue \"letsencrypt.org\""
        }
        template IN A {
            match (^|.*\.)k3scluster\.tech
            answer "{{ .Name }} 3600 IN A 109.106.138.127"
        }
        log
        forward . /etc/resolv.conf
    }
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
        import /etc/coredns/custom/*.override
    }
    import /etc/coredns/custom/*.server
  NodeHosts: |
    192.168.31.90 raspberrypi-41
    192.168.31.102 raspberrypi-51
