apiVersion: v1
kind: Service
metadata:
  name: kube-dns-lb
  namespace: kube-system
spec:
  selector:
    k8s-app: kube-dns
  ports:
    - name: dns
      protocol: UDP
      port: 53
      targetPort: 53
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
  type: LoadBalancer
