apiVersion: v1
kind: Service
metadata:
  name: redis-events-provider
  namespace: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-events-provider
  clusterIP: None  # Создает сервис Headless для доступа по DNS StatefulSet